nobank/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.user_registration, name='register'),


]

nobank/nobank/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('polls/', include('polls.urls', namespace='polls')),
    path('accounts/', include('accounts.urls', namespace="accounts"))
]

nobank/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('list/', views.polls_list, name='list'),
    # polls/details/1/
    path('details/<int:poll_id>/', views.polls_detail, name='detail'),
    # polls/details/1/vote
    path('details/<int:poll_id>/vote/', views.poll_vote, name='vote')

]

nobank/polls/models.py
from django.db import models


# Create your models here.
class Poll(models.Model):
    text = models.CharField(max_length=255)
    pub_date = models.DateField()

    def __str__(self):
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return "{} = {}".format(self.question.text[:25], self.choice_text[:25])

nobank/accounts/forms.py
from django import forms


class UserRegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', max_length=100)

nobank/nobank/views.py
from django.shortcuts import render


def home(request):
    context = {}
    return render(request, 'home.html', context)

nobank/polls/views.py
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from .models import Poll, Choice

# Create your views here.


def polls_list(request):
    """
    Renders the Poll
    :param request:
    :return:
    """
    polls = Poll.objects.all()
    context = {'polls': polls}
    return render(request, 'polls/polls_list.html', context)


def polls_detail(request, poll_id):
    """
    Render poll_detail.html
    :param request:
    :param poll_id:
    :return:
    """
    # poll = Poll.objects.get(id=poll_id)
    poll = get_object_or_404(Poll, id=poll_id)
    context = {'poll': poll}
    return render(request, 'polls/poll_detail.html', context)


def poll_vote(request, poll_id):

    poll = get_object_or_404(Poll, id=poll_id)
    choice_id = request.POST.get('choice')
    if choice_id:
        choice = Choice.objects.get(id=choice_id)
        choice.votes += 1
        choice.save()
    else:
        messages.error(request, 'No choice Was found ')
        return HttpResponseRedirect(reverse("polls:detail", args=(poll_id,)))
    return render(request, 'polls/poll_results.html', {'poll': poll})

nobank/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form action="" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" name="username" placeholder="Enter username">
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="Enter password">
                  </div>
                  <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

</div>


{% endblock %}

nobank/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">

    </form>

{% endblock %}

nobank/polls/templates/polls/poll_detail.html
{% extends 'base.html' %}


{% block content %}

 {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

<h1>Poll Detail Page</h1>
{{ poll }}

<form action="{% url 'polls:vote' poll.id %}" method="post">
    {% csrf_token %}

    {% for choice in poll.choice_set.all %}

        <input type="radio"
               name="choice"
               id="choice{{ forloop.counter }}"
               value="{{choice.id}}"/>
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <br/>

    {% endfor %}

    <input type="submit" value="Vote"/>


</form>

{% endblock %}

nobank/polls/templates/polls/poll_results.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
                <ul>
                    {% for choice in poll.choice_set.all %}
                        <li>{{choice.choice_text}} - {{choice.votes}}</li>
                    {% endfor %}
                </ul>
        </div>
    </div>


</div>

{% endblock %}

nobank/polls/templates/polls/polls_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Welcome to Poll list</h1>
    <ul>
        {% for poll in polls %}
        <li><a href="{% url 'polls:detail' poll_id=poll.id %}"> {{ poll }} </a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

nobank/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WeFun | e-services</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">

    {% block custom_css %}{% endblock %}
</head>
<body>
    {% include 'includes/navbar.html' %}
    {% block content %}
    <h1> this header tag will be overwritten by child template that defined by a block content</h1>
    {% endblock %}



<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

nobank/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block custom_css %}
<link rel='stylesheet' type='text/css' href="{% static 'css/home_styles.css' %}">
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
           <div id="home-content">
               <h1>WeFun</h1>
               <h3>The Financial e-services For Everyone!</h3>
               <hr>
               <button type="button" class="btn btn-light">Get Started!</button>
           </div>
        </div>
    </div>

</div>

{% endblock %}

nobank/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">WeFun</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{% url 'polls:list' %}">Polls</a>
          <a class="nav-item nav-link" href="#">Pricing</a>
          <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </div>
        <div class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
            {% endif %}

        </div>

      </div>
    </nav>